server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /CV.pdf {
        add_header Content-Disposition 'attachment; filename="Oscar_Carballo_CV.pdf"';
    }
}
